name: 'Release'
on:
  push:
    branches:
      - 'release'
jobs:
  release:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v3'
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: 'Use Node.js 16.0'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '16.0'
      - name: 'Set up'
        run: 'yarn install --frozen-lockfile'
      - name: 'Publish to NPM'
        run: 'yarn release'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
