name: 'Release'
on:
  workflow_dispatch:
  push:
    branches:
      - 'release'
jobs:
  release:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v3'
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: 'Use Node.js 18.0'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jamashita'
        env:
          NODE_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Set up'
        run: 'yarn install --frozen-lockfile'
      - name: 'Publish to GPR'
        run: 'yarn release'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
